/**
 * @file guards.ts
 * @description
 * This file contains utility functions related to guard AI, specifically for calculating their field of vision.
 */

import { Guard, TileType } from '../types';
import { getLineOfSight } from './pathfinding';

/**
 * Calculates the set of tiles currently visible to a guard based on their position, orientation, and status.
 * Alerted guards have a wider and longer field of vision.
 * @param {Guard} guard - The guard object.
 * @param {TileType[][]} map - The game map, used for line-of-sight checks.
 * @returns {Set<string>} A Set of coordinate strings ("x-y") for each tile visible to the guard.
 */
export const calculateGuardVision = (
    guard: Guard,
    map: TileType[][],
    isObstacleOverride?: (x: number, y: number, tile: TileType) => boolean
): Set<string> => {
    const visionTiles = new Set<string>();
    if (!map || map.length === 0 || !map[0]) return visionTiles;
    const { x, y, orientation, status } = guard;
    if (status === 'knocked_out' || (guard.knockout_timer && guard.knockout_timer > 0)) {
        return visionTiles;
    }

    // Alerted or stationary guards have enhanced vision.
    const isAlerted = status === 'permanently_alerted' || status === 'chasing_player' || guard.isStationary;
    const range = isAlerted ? 7 : 5; // How many tiles forward the guard can see.
    const widthModifier = isAlerted ? 1 : 0; // How much wider the cone is at its base.

    // The vision cone is generated by iterating in a fan-shaped pattern based on the guard's orientation.
    for (let i = 1; i <= range; i++) {
        // The width of the cone increases with distance.
        for (let j = -i - widthModifier; j <= i + widthModifier; j++) {
            let px, py;

            // Determine the coordinates of the tile to check based on orientation.
            if (orientation === 'up') { px = x + j; py = y - i; }
            else if (orientation === 'down') { px = x + j; py = y + i; }
            else if (orientation === 'left') { px = x - i; py = y + j; }
            else /* right */ { px = x + i; py = y + j; }

            // Check if the calculated coordinates are within the map boundaries.
            if (px < 0 || py < 0 || px >= map[0].length || py >= map.length) continue;

            // If there's a clear line of sight from the guard to the target tile, it's visible.
            if (getLineOfSight(guard, { x: px, y: py }, map, isObstacleOverride)) {
                visionTiles.add(`${px}-${py}`);
            }
        }
    }
    return visionTiles;
};

/**
 * Checks if a specific tile is currently visible to a guard.
 * Optimized to avoid calculating the entire field of vision if we only care about one tile.
 * @param {Guard} guard - The guard object.
 * @param {number} tileX - The x-coordinate of the target tile.
 * @param {number} tileY - The y-coordinate of the target tile.
 * @param {TileType[][]} map - The game map.
 * @returns {boolean} True if the tile is visible, false otherwise.
 */
export const canGuardSeeTile = (
    guard: Guard,
    tileX: number,
    tileY: number,
    map: TileType[][],
    isObstacleOverride?: (x: number, y: number, tile: TileType) => boolean
): boolean => {
    const { x, y, orientation, status } = guard;
    if (status === 'knocked_out' || (guard.knockout_timer && guard.knockout_timer > 0)) {
        return false;
    }

    // Alerted or stationary guards have enhanced vision.
    const isAlerted = status === 'permanently_alerted' || status === 'chasing_player' || guard.isStationary;
    const range = isAlerted ? 7 : 5; // How many tiles forward the guard can see.

    // 1. Quick Range Check (Manhattan distance loose check to fail fast)
    // Actually, bounding box is safer and faster.
    if (Math.abs(tileX - x) > range || Math.abs(tileY - y) > range) {
        return false;
    }

    // 2. Check if the tile is within the specific vision cone
    let forwardDist = 0;
    let sideDist = 0;

    if (orientation === 'up') {
        forwardDist = y - tileY;
        sideDist = tileX - x;
    } else if (orientation === 'down') {
        forwardDist = tileY - y;
        sideDist = tileX - x;
    } else if (orientation === 'left') {
        forwardDist = x - tileX;
        sideDist = tileY - y;
    } else if (orientation === 'right') {
        forwardDist = tileX - x;
        sideDist = tileY - y;
    }

    // Guard can only see things in front of them (dist > 0) and within range
    if (forwardDist < 1 || forwardDist > range) return false;

    // Check cone width
    const widthModifier = isAlerted ? 1 : 0;
    // The cone width is determined by: |sideDist| <= forwardDist + widthModifier
    if (Math.abs(sideDist) > forwardDist + widthModifier) return false;

    // 3. Check Line of Sight (Raycast)
    return getLineOfSight(guard, { x: tileX, y: tileY }, map, isObstacleOverride);
};